# Generated by Django 4.0.4 on 2022-04-14 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('date', models.DateField()),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('direction', models.CharField(choices=[('IN', 'IN'), ('OUT', 'OUT')], default='', max_length=50)),
                ('amount', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('measurement_unit', models.CharField(choices=[('Kg', 'KG'), ('Liters', 'Ltrs'), ('Units', 'Units')], default='', max_length=50)),
            ],
        ),
    ]
